name: bloc_statemanagement_demo
description: "demo_project"
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  package_info_plus: ^10.2.1
  dio: ^5.11.0
  toastification: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500

        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
  assets:
    - assets/google.png
    - assets/logo.png
